'use strict';

// ============================================================
// PRINT ORDERS — customer-facing print-on-demand (Phase: skeleton)
// ============================================================
// Mounts the vendor-neutral PrintProvider behind a small REST surface:
//   GET  /api/print/options       -> the curated menu for a page count
//   POST /api/print/quote         -> live price for a selection + address
//   POST /api/print/order         -> place an order (payment-first)
//   GET  /api/print/order/:id     -> status + tracking for one order
//
// CRITICAL ORDERING RULE (see createOrder handler): the customer payment
// must SUCCEED before we submit the print job to the vendor. Vendor billing
// always lands on Campaignia's own account, so we never submit a job we
// haven't been paid for. Stripe isn't wired yet, so payment is STUBBED here
// (payment_status='stubbed'); the sequence and failure handling are built so
// dropping Stripe into the marked seam is the only change needed.
//
// The INTERIOR PDF is generated by the client review step (the print-ready
// generator at /api/pdf/print-interior, R2-hosted) and passed as interiorPdfUrl.
// The COVER is still a request-body placeholder until the cover generator
// (later phase). Hardening note: /order trusts the supplied interiorPdfUrl for
// now; a later pass can regenerate or validate it server-side (with Stripe).

const express = require('express');
const router = express.Router();
const { getDb } = require('../database/db');
const { friendlyError } = require('../middleware/friendlyErrors');
const { getTier } = require('../middleware/tiers');
const { getPrintProvider } = require('../services/printing');
const catalog = require('../services/printing/catalog');
const { sendOrderConfirmationEmail, sendOrderProblemEmail, sendOrderFailureReport } = require('./email');
const stripeProvider = require('../services/billing/stripeProvider');

// Markup is read from app_settings ('print_markup_pct', default 10) and
// applied to the PRINT cost only -- shipping (and tax) pass through at cost.
const DEFAULT_PRINT_MARKUP_PCT = 10;
async function getPrintMarkupPct(db) {
  try {
    const r = await db.prepare("SELECT value FROM app_settings WHERE setting_key = ?").get('print_markup_pct');
    const p = r && r.value != null ? parseFloat(r.value) : NaN;
    return Number.isFinite(p) && p >= 0 ? p : DEFAULT_PRINT_MARKUP_PCT;
  } catch (e) { return DEFAULT_PRINT_MARKUP_PCT; }
}
function applyPrintMarkup(totalCost, printCost, pct) {
  var charge = Number(totalCost || 0) + Number(printCost || 0) * (pct / 100);
  return Math.round(charge * 100) / 100;
}
// Customer-facing charge breakdown.
// v3.0.425 -- MARKUP ON THE PRINT COST BEFORE TAX, AND TAX SHOWN AS ITS OWN LINE.
// The markup used to be applied to Lulu's TAX-INCLUSIVE print cost, so a share of every markup was
// a markup on tax -- small money, wrong on principle, and it made a tax line impossible to reconcile
// with the total. Tax now passes through untouched and is displayed.
// THE TOTAL IS ANCHORED ON WHAT LULU ACTUALLY BILLS US (quote.totalCost) plus the markup, NOT on the
// sum of the parts. If Lulu ever adds a fee that is in its total and in none of the parts we read,
// summing the parts would quietly charge the customer less than the order costs. The residual is
// folded into the print line so the breakdown still adds up exactly, and logged so it cannot hide.
function markedCharge(quote, pct) {
  var r2 = function (n) { return Math.round(Number(n || 0) * 100) / 100; };
  var shipping = r2(quote.shippingCostExclTax != null ? quote.shippingCostExclTax : quote.shippingCost);
  var tax = r2(quote.taxCost);
  var providerTotal = Number(quote.totalCost || 0);
  var totalExcl = Number(quote.totalCostExclTax != null ? quote.totalCostExclTax : (providerTotal - tax)) || 0;
  // v3.0.429 -- THE MARKUP BASE IS EVERYTHING THAT IS NOT SHIPPING AND NOT TAX.
  // A real Lulu quote came back as 8.59 print + 5.69 shipping + 1.20 tax against a total of 16.23:
  // 0.75 unaccounted, which is a provider fee we do not read as its own field. v3.0.425 folded that
  // residual onto the print line at cost. Ian, 2026-08-05: the fee is just part of the price, nobody
  // cares about a separate line, and the markup should apply to it too.
  // Deriving the base from the TOTAL rather than adding up the parts means an unread fee can never
  // again sit outside the markup, whatever Lulu adds next. Shipping still passes at cost, and tax is
  // never marked up -- that was the whole point of v3.0.425.
  var markupBase = r2(totalExcl - shipping);
  if (!(markupBase > 0)) markupBase = r2(quote.printCostExclTax != null ? quote.printCostExclTax : quote.printCost);
  var customerCharge = r2(providerTotal + markupBase * (Number(pct || 0) / 100));
  var printMarked = r2(markupBase * (1 + Number(pct || 0) / 100));
  // Rounding only: the three displayed lines must add up to the charge exactly.
  var residual = r2(customerCharge - (printMarked + shipping + tax));
  if (residual !== 0) printMarked = r2(printMarked + residual);
  return {
    printAtCost: r2(markupBase),
    printMarked: printMarked,
    shipping: shipping,
    tax: tax,
    customerCharge: customerCharge,
  };
}
// v3.0.425 -- ONE LINE PER QUOTE, SO THE TAX QUESTION IS ANSWERABLE FROM A LOG.
// quote.raw was never logged and never stored, so nothing in the system could say whether Lulu was
// reporting tax at all. A tax of 0.00 here means we are NOT collecting it and the margin is paying
// for it; a tax around 8 percent of the order means it was always in the price and merely unshown.
function logQuoteTax(where, quote, m) {
  try {
    console.log('[print-quote] ' + where + ': print ' + Number(quote.printCostExclTax || 0).toFixed(2)
      + ' + shipping ' + Number(quote.shippingCostExclTax || 0).toFixed(2)
      + ' + fees ' + (Number(quote.totalCostExclTax || 0) - Number(quote.printCostExclTax || 0) - Number(quote.shippingCostExclTax || 0)).toFixed(2)
      + ' + tax ' + Number(quote.taxCost || 0).toFixed(2)
      + ' = Lulu total ' + Number(quote.totalCost || 0).toFixed(2)
      + ' ' + (quote.currency || 'USD') + '; customer charged ' + Number(m.customerCharge || 0).toFixed(2)
      + (Number(quote.taxCost || 0) > 0 ? '' : '  [NO TAX REPORTED -- see TD-222]'));
  } catch (e) {}
}

// v3.0.782 -- TD-576. CAN THE PRINTER ACTUALLY GET THESE FILES?
//
// Lulu does not receive our PDFs, it DOWNLOADS them from the urls we hand over, some time
// after the customer has paid. Everything between those two moments is unverified: an object
// that never landed, a signed url whose expiry has passed, a bucket prefix that is not public.
// Every one of those becomes a vendor rejection AFTER the charge, which is the one shape of
// failure this product must not have.
//
// So we do what the vendor will do, from the same side of the network, before charging: ask
// for the file. HEAD first, because it costs nothing; some object stores answer HEAD with 403
// or 405 while serving GET perfectly well, so a refusal falls back to a one-byte ranged GET
// rather than being believed.
//
// THE SNEAKY CASE IS A 200. A missing object behind a proxy answers 200 with an HTML error
// page, which passes every naive "is it reachable" test and then fails at the printer as a
// corrupt PDF. Content-type is therefore checked as well as status -- html is treated as
// absent, because that is what it is.
//
// An INCONCLUSIVE answer is not a refusal. If the check itself times out or throws, the order
// proceeds: refusing to sell someone a book because our own probe was slow would be a worse
// bug than the one this prevents. Only a definite negative stops the sale.
var ORDER_FILE_PROBE_MS = 15000;
async function vendorCanFetch(url) {
  var out = { ok: false, conclusive: false, status: 0, type: '', detail: '' };
  if (!(typeof url === 'string' && /^https?:\/\//i.test(url))) {
    out.conclusive = true; out.detail = 'not a fetchable url';
    return out;
  }
  var ctl = null, timer = null;
  try {
    ctl = new AbortController();
    timer = setTimeout(function () { try { ctl.abort(); } catch (e) {} }, ORDER_FILE_PROBE_MS);
    var res = await fetch(url, { method: 'HEAD', signal: ctl.signal, redirect: 'follow' });
    if (res.status === 403 || res.status === 405 || res.status === 501) {
      res = await fetch(url, { method: 'GET', headers: { Range: 'bytes=0-0' }, signal: ctl.signal, redirect: 'follow' });
    }
    out.status = res.status;
    out.type = String(res.headers.get('content-type') || '').toLowerCase();
    if (res.status >= 200 && res.status < 300) {
      if (out.type.indexOf('html') !== -1) {
        out.conclusive = true; out.detail = 'the url answers with a web page, not a file';
      } else {
        out.ok = true; out.conclusive = true;
      }
    } else if (res.status >= 400 && res.status < 500) {
      out.conclusive = true; out.detail = 'the printer would get HTTP ' + res.status;
    } else {
      out.detail = 'HTTP ' + res.status;   // 5xx: the host is unwell, not the file. Inconclusive.
    }
  } catch (e) {
    out.detail = (e && e.name === 'AbortError') ? 'the check timed out' : ((e && e.message) || 'unreachable');
  } finally {
    if (timer) clearTimeout(timer);
  }
  return out;
}
// v3.0.786 -- TD-587. GO AND SEE WHETHER THE JOB WE MAY HAVE CREATED EXISTS.
//
// The one thing that turns a lost reply into a non-event. Asks Lulu for the job stamped with this
// order's external_id and, if it is there, records it exactly as the successful path would have.
//
// RETURNS one of three answers, and the third is the point:
//   { found: true,  ... }  the job exists and the row now holds its id
//   { found: false }       Lulu answered and has nothing -- the order really was not created
//   { unknown: true }      Lulu could not be asked, so nothing has been learned
// Collapsing the last two is the bug this exists to fix, one level down in _fetch. A recovery that
// reports "no job" because the network was unwell would send a reader to press Reorder on a book
// already in production.
//
// IDEMPOTENT AND SAFE TO CALL OFTEN. It only ever WRITES a provider_order_id where there is none,
// and the UPDATE says so in its WHERE clause, so two callers racing cannot produce two answers.
async function recoverPrintJob(db, row) {
  if (!row) return { unknown: true };
  if (row.provider_order_id) return { found: true, providerOrderId: row.provider_order_id, already: true };
  var externalId = row.external_id || ('po-' + row.id);
  try {
    var provider = getPrintProvider();
    if (typeof provider.findOrderByExternalId !== 'function') return { unknown: true };
    var live = await provider.findOrderByExternalId(externalId);
    if (!live || !live.providerOrderId) return { found: false };
    await db.prepare(
      'UPDATE print_orders SET provider_order_id = ?, status = ?, tracking_url = ?, carrier = ?, ' +
      'error = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND provider_order_id IS NULL'
    ).run(live.providerOrderId, live.status || 'created', live.trackingUrl || null, live.carrier || null, row.id);
    row.provider_order_id = live.providerOrderId;
    row.status = live.status || 'created';
    row.error = null;
    try {
      console.log('[order-recover] ' + externalId + ' was already at the printer as job ' +
        live.providerOrderId + ' -- adopted' +
        ((live.duplicateCount > 1) ? (' (WARNING: ' + live.duplicateCount + ' jobs carry this external id)') : ''));
    } catch (e) {}
    return { found: true, providerOrderId: live.providerOrderId, status: row.status,
             duplicateCount: live.duplicateCount || 1 };
  } catch (e) {
    try { console.warn('[order-recover] could not ask the printer about ' + externalId + ': ' + ((e && e.message) || e)); } catch (e2) {}
    return { unknown: true, detail: (e && e.message) || String(e) };
  }
}
// v3.0.787 -- TD-587b. NARROWED TO THE STATES THAT ACTUALLY NEED IT.
// v3.0.786 asked about any paid order with no job id -- which includes an order still being
// submitted, because fulfillPrintOrder marks the row paid and THEN submits. On a slow vendor that
// window is a minute and a half, and the sweep would race a request that is still in flight.
// Harmless (the write is guarded on provider_order_id IS NULL) but pointless, and it muddies the
// log with lookups for orders that are simply not finished yet.
// The AUTOMATIC triggers use this. The BUTTON uses orderCanBeChecked below, which is wider.
function orderNeedsRecovery(row) {
  return !!(row && !row.provider_order_id &&
    (row.payment_status === 'paid' || row.payment_status === 'refunded') &&
    (row.status === 'order_failed' || row.status === 'order_unknown'));
}
// The button may ask about ANY paid order with no job, including one stranded at 'paid' because
// the process died between the payment write and the submit. Nothing automatic will ever look at
// that row -- it never reaches a failure state -- so a deliberate human check is its only way
// back, and a human pressing a button cannot race an in-flight submit the way a sweep can.
function orderCanBeChecked(row) {
  return !!(row && !row.provider_order_id &&
    (row.payment_status === 'paid' || row.payment_status === 'refunded'));
}
// v3.0.787 -- TD-588. KEEP A LIVE ORDER CURRENT, which is how tracking ever appears.
//
// getOrderStatus has always known how to read tracking and GET /order/:id has always known how to
// store it -- and NOTHING IN THE CLIENT CALLS THAT ROUTE. The orders screen reads the list, which
// reads the database and asks the vendor nothing. So `tracking_url` stayed null forever, the card
// said "Awaiting Tracking" indefinitely, and the Track Shipment link could not appear on any
// order however far it got. A correct function with no caller, the same shape as TD-585's
// _skuError and the v3.0.726 tour.
//
// Only for orders that are LIVE AND UNFINISHED: shipped and delivered are terminal, and a
// rejected or cancelled job will not change on its own either. Best-effort throughout -- a vendor
// that is slow or down must never stop an order rendering.
var ORDER_LIVE_STATES = ['created', 'accepted', 'in_production', 'paid'];
function orderIsLive(row) {
  return !!(row && row.provider_order_id && ORDER_LIVE_STATES.indexOf(String(row.status)) !== -1);
}
async function refreshLiveOrder(db, row) {
  if (!orderIsLive(row)) return false;
  try {
    var provider = getPrintProvider();
    var live = await provider.getOrderStatus(row.provider_order_id);
    if (!live) return false;
    var _st = live.status || row.status;
    var _url = live.trackingUrl || row.tracking_url || null;
    var _num = live.trackingNumber || row.tracking_number || null;
    var _car = live.carrier || row.carrier || null;
    // Write only when something actually moved: an UPDATE per render would churn updated_at and
    // make "when did this last change" meaningless.
    if (_st === row.status && _url === (row.tracking_url || null) &&
        _num === (row.tracking_number || null) && _car === (row.carrier || null)) return false;
    await db.prepare(
      'UPDATE print_orders SET status = ?, tracking_url = ?, tracking_number = ?, carrier = ?, ' +
      'updated_at = CURRENT_TIMESTAMP WHERE id = ?'
    ).run(_st, _url, _num, _car, row.id);
    row.status = _st; row.tracking_url = _url; row.tracking_number = _num; row.carrier = _car;
    return true;
  } catch (e) {
    try { console.warn('[order-refresh] ' + (row.external_id || row.id) + ': ' + ((e && e.message) || e)); } catch (e2) {}
    return false;
  }
}
function requireSession(req, res, next) {
  if (!req.session || !req.session.userId) {
    return res.status(401).json({ error: 'Not authenticated' });
  }
  next();
}

// Map the public request body to a neutral OrderRequest the provider takes.
function buildOrderRequest(body, spec, externalId, contactEmail) {
  const s = body.shipTo || {};
  return {
    externalId: externalId,
    title: body.title || 'Campaignia',
    contactEmail: contactEmail || body.contactEmail || '',
    interiorPdfUrl: body.interiorPdfUrl || '',
    coverPdfUrl: body.coverPdfUrl || '',
    spec: spec,
    quantity: Math.max(1, parseInt(body.quantity, 10) || 1),
    shippingLevel: body.shippingLevel || 'cheapest',
    shipTo: {
      name: s.name, street1: s.street1, street2: s.street2,
      city: s.city, postcode: s.postcode, stateCode: s.stateCode,
      countryCode: s.countryCode, phone: s.phone,
    },
  };
}

// Same neutral OrderRequest, but rebuilt from a stored print_orders row (used by
// the webhook fulfillment, where there is no request body).
function buildOrderRequestFromRow(row, spec, externalId, contactEmail) {
  return {
    externalId: externalId,
    title: row.book_title || row.order_name || 'Campaignia',
    contactEmail: contactEmail || '',
    interiorPdfUrl: row.interior_pdf_url || '',
    coverPdfUrl: row.cover_pdf_url || '',
    spec: spec,
    quantity: Math.max(1, parseInt(row.quantity, 10) || 1),
    shippingLevel: row.shipping_level || 'cheapest',
    shipTo: {
      name: row.ship_name, street1: row.ship_street1, street2: row.ship_street2,
      city: row.ship_city, postcode: row.ship_postcode, stateCode: row.ship_state,
      countryCode: row.ship_country, phone: row.ship_phone,
    },
  };
}

// ------------------------------------------------------------
// GET /options?pageCount=76  -> bindings that fit + color/finish axes.
// ------------------------------------------------------------
// v3.0.784 -- TD-585. The paper list depends on the ink, so the current selection comes with the
// request. Absent -> the catalog reports the conservative list, which is the right direction: an
// option that appears once you pick black and white is a smaller surprise than one that is
// offered and then refused at the price.
router.get('/options', requireSession, function (req, res) {
  const pageCount = parseInt(req.query.pageCount, 10);
  if (!(pageCount > 0)) return res.status(400).json({ error: 'pageCount required' });
  const sel = { colorTier: req.query.colorTier || req.query.color || undefined };
  res.json(catalog.optionsForPageCount(pageCount, sel));
});

// ------------------------------------------------------------
// GET /novel-info/:campaignId  -> campaign name, the versions the caller
// may order (canonical + members), and a page-count ESTIMATE.
//
// Version rules: canonical is always orderable. A DM may also order any
// player's version (those who have one); a player may order only their own.
// ------------------------------------------------------------
router.get('/novel-info/:campaignId', requireSession, async function (req, res) {
  try {
    const db = await getDb();
    const campaignId = parseInt(req.params.campaignId, 10);
    const userId = req.session.userId;

    const camp = await db.prepare('SELECT id, name, allow_player_novel_access FROM campaigns WHERE id = ?').get(campaignId);
    if (!camp) return res.status(404).json({ error: 'Campaign not found' });
    const mem = await db.prepare('SELECT role FROM campaign_members WHERE campaign_id = ? AND user_id = ?').get(campaignId, userId);
    if (!mem) return res.status(403).json({ error: 'Not a member of this campaign' });
    const isDm = mem.role === 'dm';
    if (!isDm && !camp.allow_player_novel_access) {
      return res.status(403).json({ error: 'Graphic novel access is disabled for players in this campaign' });
    }

    const versions = [{ kind: 'canonical', userId: null, name: 'Canonical (Story Master)' }];
    if (isDm) {
      const rows = await db.prepare(
        'SELECT u.id AS user_id, u.name, u.email FROM campaign_members cm JOIN users u ON u.id = cm.user_id ' +
        "WHERE cm.campaign_id = ? AND cm.role = 'player' AND EXISTS(" +
        'SELECT 1 FROM session_forks sf JOIN sessions s ON s.id = sf.session_id ' +
        "WHERE s.campaign_id = ? AND sf.user_id = u.id AND sf.role = 'player') ORDER BY u.name ASC"
      ).all(campaignId, campaignId);
      rows.forEach(function (r) {
        versions.push({ kind: 'member', userId: r.user_id, name: (r.name || r.email) + ' (member)' });
      });
    } else {
      const me = await db.prepare('SELECT name FROM users WHERE id = ?').get(userId);
      versions.push({ kind: 'member', userId: userId, name: 'My version' + (me && me.name ? ' (' + me.name + ')' : '') });
    }

    // Page-count ESTIMATE only. The true printed count is set when the
    // print-ready PDF is generated (that generator is the next milestone);
    // ~1 panel/page from the campaign's moment count is close enough to gate
    // which bindings are offered.
    const cnt = await db.prepare(
      'SELECT COUNT(*) AS c FROM moments m JOIN sessions s ON s.id = m.session_id WHERE s.campaign_id = ?'
    ).get(campaignId);
    const moments = Number((cnt && cnt.c) || 0);
    const pageEstimate = Math.max(8, moments);

    res.json({ campaignName: camp.name, role: mem.role, versions: versions, pageEstimate: pageEstimate, momentCount: moments, estimated: true });
  } catch (e) {
    res.status(500).json({ error: 'Server error', detail: friendlyError(e, '') });
  }
});

// ------------------------------------------------------------
// POST /quote  body: { selection:{binding,colorTier,coverFinish}, pageCount,
//                      quantity, shipTo, shippingLevel }
// Returns a live vendor quote + the customer-facing charge (cost + margin).
// ------------------------------------------------------------
router.post('/quote', requireSession, async function (req, res) {
  try {
    const { selection, pageCount } = req.body || {};
    const built = catalog.buildSpec(selection, parseInt(pageCount, 10));
    if (!built.ok) return res.status(400).json({ error: 'Invalid selection', details: built.errors });

    const provider = getPrintProvider();
    const orderReq = buildOrderRequest(req.body, built.spec, 'quote', null);
    const quote = await provider.getQuote(orderReq);
    const db = await getDb();
    const pct = await getPrintMarkupPct(db);
    const _m = markedCharge(quote, pct);
    logQuoteTax('quote', quote, _m);

    res.json({
      podPackageId: provider._packageId ? provider._packageId(built.spec) : undefined,
      printedPageCount: built.spec.pageCount,
      providerCost: quote.totalCost,
      currency: quote.currency,
      customerCharge: _m.customerCharge,
      markupPct: pct,
      breakdown: { print: _m.printMarked, printAtCost: _m.printAtCost, shipping: _m.shipping, tax: _m.tax },
      providerTax: quote.taxCost,
    });
  } catch (e) {
    res.status(502).json({ error: 'Quote failed', detail: friendlyError(e, '') });
  }
});

// ------------------------------------------------------------
// POST /order  body: { campaignId?, sessionId?, selection, pageCount,
//                      quantity, shipTo, shippingLevel,
//                      interiorPdfUrl, coverPdfUrl, title }
//
// Sequence: validate -> fresh quote -> CHARGE CUSTOMER (stubbed) ->
// persist -> submit to vendor -> reconcile. If the vendor submit fails
// after a (real) charge, the order is marked order_failed for refund.
// ------------------------------------------------------------
router.post('/order', requireSession, async function (req, res) {
  const userId = req.session.userId;
  const body = req.body || {};
  // Watermarked books (the Free Trial tier) can't be ordered as physical
  // prints. Enforce server-side so the client-side button hide can't be
  // bypassed. Keyed on the account tier's watermark flag.
  try {
    const _wdb = await getDb();
    const _wu = await _wdb.prepare('SELECT tier FROM users WHERE id = ?').get(userId);
    const _wt = getTier((_wu && _wu.tier) || 'copper');
    if (_wt && _wt.watermark) {
      return res.status(403).json({ error: "This book is watermarked and can't be ordered as a physical print. Upgrade to a paid plan to remove the watermark and order." });
    }
  } catch (e) { /* lookup failure -> fall through to the normal flow */ }
  const built = catalog.buildSpec(body.selection, parseInt(body.pageCount, 10));
  if (!built.ok) return res.status(400).json({ error: 'Invalid selection', details: built.errors });
  // Global Max Pages Per Print limit (applies to all layouts). Block over-limit
  // orders before they reach the printer.
  try {
    const _ppdb = await getDb();
    const _ppRow = await _ppdb.prepare("SELECT value FROM app_settings WHERE setting_key = ?").get('max_pages_per_print');
    var _ppMax = _ppRow && _ppRow.value != null ? parseInt(_ppRow.value, 10) : 250;
    if (!Number.isFinite(_ppMax)) _ppMax = 250;
    var _ppCount = parseInt(body.pageCount, 10);
    if (Number.isFinite(_ppCount) && _ppCount > _ppMax) {
      return res.status(413).json({ error: 'PAGE_LIMIT', pages: _ppCount, maxPages: _ppMax, message: 'This book is ' + _ppCount + ' pages, which is over the current ' + _ppMax + '-page limit for a single book. To make it fit, open your Sessions list and uncheck some sessions using the "Include in Print" checkbox, then try again, or split it into multiple smaller books.' });
    }
  } catch (e) { /* count lookup failure -> fall through */ }
  if (!body.interiorPdfUrl || !body.coverPdfUrl) {
    return res.status(400).json({ error: 'interiorPdfUrl and coverPdfUrl are required' });
  }
  // v3.0.782 -- TD-576. Before the quote, before the row, before the Checkout session: no
  // money may move for a book whose files the printer demonstrably cannot collect. Placed
  // here so a definite negative costs nothing at all -- no vendor call, no database row.
  try {
    var _fInt = await vendorCanFetch(body.interiorPdfUrl);
    var _fCov = await vendorCanFetch(body.coverPdfUrl);
    var _bad = [];
    if (_fInt.conclusive && !_fInt.ok) _bad.push('interior (' + _fInt.detail + ')');
    if (_fCov.conclusive && !_fCov.ok) _bad.push('cover (' + _fCov.detail + ')');
    if (_bad.length) {
      console.error('[order] refused before payment -- unfetchable print file(s): ' + _bad.join('; '));
      return res.status(409).json({
        error: 'FILES_UNREACHABLE',
        message: 'We could not hand these print files to the printer, so nothing has been charged. ' +
                 'Open the Publish page, build the book again, and try the order once more.',
        detail: _bad.join('; ')
      });
    }
  } catch (e) {
    // The probe itself failing is NOT a refusal -- see vendorCanFetch.
    try { console.error('[order] file probe failed, continuing: ' + ((e && e.message) || e)); } catch (e2) {}
  }
  if (!stripeProvider.isConfigured()) {
    return res.status(503).json({ error: 'billing_unconfigured' });
  }

  try {
    const db = await getDb();
    const provider = getPrintProvider();
    const u = await db.prepare('SELECT name, email FROM users WHERE id = ?').get(userId);
    const contactEmail = u && u.email ? u.email : null;

    // 1) Fresh quote at checkout time (prices/shipping move).
    const quoteReq = buildOrderRequest(body, built.spec, 'quote', contactEmail);
    const quote = await provider.getQuote(quoteReq);
    const pct = await getPrintMarkupPct(db);
    const _mo = markedCharge(quote, pct);
    logQuoteTax('order', quote, _mo);
    const customerCharge = _mo.customerCharge;
    const podPackageId = provider._packageId ? provider._packageId(built.spec) : null;

    // 2) Persist the order as pending_payment BEFORE creating the Checkout
    //    session, so the webhook can find it by id and we keep a record even if
    //    the customer abandons payment.
    const s = body.shipTo || {};
    const orderName = (body.orderName != null ? String(body.orderName) : '').trim().slice(0, 200) || null;
    const bookTitle = (body.bookTitle != null ? String(body.bookTitle) : '').trim().slice(0, 200) || null;
    const sourceUserId = body.sourceUserId ? parseInt(body.sourceUserId, 10) : null;
    const sourceKind = sourceUserId ? 'member' : 'canonical';
    let campaignName = null, sourceUserName = null;
    if (body.campaignId) {
      const c = await db.prepare('SELECT name FROM campaigns WHERE id = ?').get(body.campaignId);
      campaignName = c && c.name ? c.name : null;
    }
    if (sourceUserId) {
      const su = await db.prepare('SELECT name, email FROM users WHERE id = ?').get(sourceUserId);
      sourceUserName = su ? (su.name || su.email || null) : null;
    }
    // v3.0.667 -- TD-465. THE SNAPSHOT OF WHAT WAS SOLD.
    //
    // Ian, 2026-08-17: "if we need to store orders differently to begin with that is fine.... Maybe
    // a JSON field in the db if that would help holding all the details."
    //
    // Taken from built.spec and the request AT THIS MOMENT, because this is the only moment it is
    // all true at once. paper is the one that forced this: it swaps the vendor SKU and had no
    // column, so a cream book was recorded as nothing.
    //
    // coverImageUrl is the DISPLAY cover, not cover_pdf_url -- that one is the print wrap, back and
    // spine and front as a PDF, which no card can show. Captured here so My Orders can one day show
    // the book AS IT WAS SOLD; showing today's cover against an old order would be the same lie this
    // snapshot exists to prevent.
    //
    // NOTHING READS INTO THIS BLOB. Reorder prefers it and falls back to the columns, so an order
    // placed before today still reorders -- just without paper, which is unrecoverable for those.
    let _orderSpec = null;
    try {
      _orderSpec = JSON.stringify({
        v: 1,
        at: new Date().toISOString(),
        selection: {
          binding: built.spec.binding,
          colorTier: (body.selection || {}).colorTier || null,
          coverFinish: built.spec.coverFinish,
          paper: built.spec.paper || null,
          pageCount: built.spec.pageCount,
          quantity: quoteReq.quantity,
          shippingLevel: quoteReq.shippingLevel
        },
        book: {
          title: bookTitle,
          orderName: orderName,
          campaignId: body.campaignId || null,
          sessionId: body.sessionId || null,
          sourceUserId: sourceUserId,
          sourceKind: sourceKind,
          coverImageUrl: body.coverImageUrl || null,
          layoutStyle: body.layoutStyle || null,
          customOpts: body.customOpts || null
        },
        files: { interior: body.interiorPdfUrl, cover: body.coverPdfUrl },
        podPackageId: podPackageId
      });
    } catch (e) { _orderSpec = null; }

    const ins = await db.prepare(
      `INSERT INTO print_orders
        (user_id, campaign_id, session_id, provider, pod_package_id,
         binding, color_tier, cover_finish, paper, order_spec, page_count, quantity,
         interior_pdf_url, cover_pdf_url,
         ship_name, ship_street1, ship_street2, ship_city, ship_state,
         ship_postcode, ship_country, ship_phone, shipping_level,
         provider_cost, currency, customer_charge, payment_status, status,
         order_name, book_title, campaign_name, source_kind, source_user_id, source_user_name,
         provider_tax, provider_cost_excl_tax, markup_pct)
       VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`
    ).run(
      userId, body.campaignId || null, body.sessionId || null, provider.name, podPackageId,
      built.spec.binding, (body.selection || {}).colorTier, built.spec.coverFinish,
      built.spec.paper || null, _orderSpec,
      built.spec.pageCount, quoteReq.quantity,
      body.interiorPdfUrl, body.coverPdfUrl,
      s.name || null, s.street1 || null, s.street2 || null, s.city || null, s.stateCode || null,
      s.postcode || null, s.countryCode || null, s.phone || null, quoteReq.shippingLevel,
      quote.totalCost, quote.currency, customerCharge, 'unpaid', 'pending_payment',
      orderName, bookTitle, campaignName, sourceKind, sourceUserId, sourceUserName,
      // v3.0.425 -- KEEP THE TAX WITH THE ORDER. It cannot be reconstructed later: Lulu prices move,
      // and a quote is only true at the moment it was taken. If a remittance obligation ever lands,
      // this column is the history, and there is no way to backfill a column that was never written.
      quote.taxCost != null ? quote.taxCost : null,
      quote.totalCostExclTax != null ? quote.totalCostExclTax : null,
      pct
    );
    const orderId = ins.lastInsertRowid;
    const externalId = 'po-' + orderId;
    await db.prepare('UPDATE print_orders SET external_id = ? WHERE id = ?').run(externalId, orderId);

    // 3) Create the Stripe Checkout session (one-time). The amount is the
    //    server-computed customerCharge. On payment, checkout.session.completed
    //    fires and the webhook (fulfillPrintOrder) submits the job to the
    //    vendor -- payment-first, so we never print what we were not paid for.
    const base = (process.env.PUBLIC_BASE_URL || '').replace(/\/+$/, '');
    const amountCents = Math.round(Number(customerCharge) * 100);
    const descBits = [bookTitle || orderName || 'Campaignia book'];
    if (quoteReq.quantity > 1) descBits.push('x' + quoteReq.quantity);
    const session = await stripeProvider.createOneTimeCheckout({
      amountCents: amountCents,
      currency: (quote.currency || 'usd').toLowerCase(),
      description: descBits.join(' '),
      userId: userId,
      customerEmail: contactEmail,
      metadata: { kind: 'print_order', order_id: String(orderId), user_id: String(userId) },
      successUrl: base + '/app.html?order=success',
      cancelUrl: base + '/app.html?order=cancel'
    });
    await db.prepare('UPDATE print_orders SET stripe_session_id = ? WHERE id = ?').run(session.id, orderId);

    return res.json({ url: session.url, orderId: orderId, externalId: externalId, customerCharge: customerCharge, currency: quote.currency });
  } catch (e) {
    if (e && e.code === 'BILLING_UNCONFIGURED') return res.status(503).json({ error: 'billing_unconfigured' });
    return res.status(502).json({ error: 'Order failed', detail: friendlyError(e, '') });
  }
});

// ------------------------------------------------------------
// GET /order/:id  -> the caller's order, status refreshed from the vendor.
// ------------------------------------------------------------
router.get('/order/:id', requireSession, async function (req, res) {
  try {
    const db = await getDb();
    const row = await db.prepare('SELECT * FROM print_orders WHERE id = ?').get(parseInt(req.params.id, 10));
    if (!row || row.user_id !== req.session.userId) return res.status(404).json({ error: 'Not found' });

    if (row.provider_order_id) {
      // v3.0.787 -- TD-588. Was an inline copy that wrote only on a STATUS change, so a job that
      // shipped without changing state -- or that gained tracking a moment after SHIPPED landed --
      // never got its url stored. It also never captured the tracking NUMBER at all. One helper
      // now, shared with the list sweep, so the two cannot drift.
      await refreshLiveOrder(db, row);
    } else if (orderNeedsRecovery(row)) {
      // v3.0.786 -- TD-587. The missing else. This branch has always refreshed an order that HAS a
      // job id; an order that is paid and has none is the one that most needs asking about.
      try { await recoverPrintJob(db, row); } catch (_e2) {}
    }
    res.json(row);
  } catch (e) {
    res.status(500).json({ error: 'Server error', detail: friendlyError(e, '') });
  }
});

// ------------------------------------------------------------
// GET /orders -> the caller's print orders (most recent first).
// ------------------------------------------------------------
router.get('/orders', requireSession, async function (req, res) {
  try {
    const db = await getDb();
    const rows = await db.prepare(
      // v3.0.665 -- TD-464. THE COLUMNS A REORDER NEEDS, and no more.
      // Reorder restores a past order's FORMAT, SHIPPING and PRINT FILES onto the Order tab. All of
      // it is already on the row; the list simply was not sending it. Everything added here is the
      // caller's own data about their own order -- the WHERE clause is user_id -- and ship_name was
      // already going out, so the address is not a new category of thing to leak.
      // campaign_id is the one that decides whether Reorder can be offered at all: deleting a
      // campaign NULLs it (routes/campaigns.js) rather than deleting the order, so a NULL here means
      // the book behind this order is gone.
      `SELECT id, external_id, provider_order_id, order_name, book_title, campaign_name,
              campaign_id, session_id, source_kind, source_user_id, source_user_name,
              binding, color_tier, cover_finish, paper, order_spec, error,
              page_count, quantity, customer_charge, currency, payment_status,
              status, tracking_url, tracking_number, carrier, card_brand, card_last4,
              ship_name, ship_street1, ship_street2, ship_city, ship_state, ship_postcode,
              ship_country, ship_phone, shipping_level,
              interior_pdf_url, cover_pdf_url, created_at, updated_at
         FROM print_orders WHERE user_id = ? ORDER BY id DESC`
    ).all(req.session.userId);
    // v3.0.786 -- TD-587. RELOADING THIS SCREEN GOES AND LOOKS.
    // Ian: "I should be able to put our order number back... and it should go find it if I reload
    // the order screen?" -- yes, and this is where that happens.
    //
    // BOUNDED, deliberately. Each recovery is a live call to Lulu, and a list route that fans out
    // one per row would make a long order history slow and would hammer the vendor for no benefit.
    // Normally NOTHING matches: a paid order with no job id is the rare case. Oldest first, because
    // if there is ever a backlog the oldest is the one closest to being forgotten.
    try {
      var _needy = (rows || []).filter(orderNeedsRecovery).slice(-3);
      for (var _i = 0; _i < _needy.length; _i++) await recoverPrintJob(db, _needy[_i]);
      // v3.0.787 -- TD-588. AND BRING LIVE ORDERS UP TO DATE, which is what makes tracking appear.
      // Same bounded shape and the same reason: only orders that are at the printer and not yet
      // finished, newest first because that is what someone opening this screen is looking at.
      var _live = (rows || []).filter(orderIsLive).slice(0, 5);
      for (var _j = 0; _j < _live.length; _j++) await refreshLiveOrder(db, _live[_j]);
    } catch (_e) { /* never let a recovery attempt stop the list rendering */ }
    res.json({ orders: rows || [] });
  } catch (e) {
    res.status(500).json({ error: 'Could not load orders', detail: friendlyError(e, '') });
  }
});

// v3.0.786 -- TD-587. ASK THE PRINTER, ON DEMAND.
// The manual version of the recovery above, so the step Ian performed with a SQL UPDATE on po-7 is
// a button. Also the honest answer to "did it run?" -- the automatic triggers are silent when they
// find nothing, and a reader with a stuck order needs to be able to make something happen and see
// what it said.
// Answers in the reader's terms, and NEVER conflates "the printer has no such job" with "the
// printer could not be reached": those need opposite next steps.
router.post('/orders/:id/recover', requireSession, async function (req, res) {
  try {
    const db = await getDb();
    const id = parseInt(req.params.id, 10);
    if (!Number.isFinite(id)) return res.status(400).json({ error: 'Bad order id' });
    const row = await db.prepare('SELECT * FROM print_orders WHERE id = ?').get(id);
    if (!row || row.user_id !== req.session.userId) return res.status(404).json({ error: 'Order not found' });
    if (row.provider_order_id) {
      return res.json({ ok: true, found: true, already: true, providerOrderId: row.provider_order_id,
        message: 'This order is already with the printer as job ' + row.provider_order_id + '.' });
    }
    if (!orderCanBeChecked(row)) {
      return res.json({ ok: true, found: false, notPaid: true,
        message: 'This order was never paid for, so nothing was ever sent to the printer.' });
    }
    const out = await recoverPrintJob(db, row);
    if (out.found) {
      return res.json({ ok: true, found: true, providerOrderId: out.providerOrderId, status: out.status,
        duplicateCount: out.duplicateCount || 1,
        message: 'Found it. Your book is with the printer as job ' + out.providerOrderId + '.' });
    }
    if (out.unknown) {
      return res.json({ ok: true, unknown: true,
        message: 'The printer could not be reached just now, so we still do not know. Nothing has changed. Please try again in a few minutes.' });
    }
    return res.json({ ok: true, found: false,
      message: 'The printer has no job for this order, so it really was not sent. You have been charged and it is safe to order again.' });
  } catch (e) {
    log500('order-recover', req, e);
    return res.status(500).json({ error: 'Could not check with the printer.' });
  }
});

// ------------------------------------------------------------
// DELETE /orders/:id -- remove an order that was never paid for, and its two print files.
//
// v3.0.668 -- TD-470. Ian, 2026-08-17: "On Abandoned orders we should give them a delete button...
// I don't want a bunch of stuff to pile up here."
//
// THE PILE-UP IS ALREADY REAL. The order row is written BEFORE the Stripe session so the webhook has
// something to attach payment to, and nothing has ever aged one out -- so every abandoned checkout,
// including every test one, is sitting in My Orders labelled pending_payment forever, holding two
// PDFs in the bucket.
//
// NEVER PAID, AND NEVER PAID FOR. The test is payment_status, not status: a refunded order WAS paid
// for and is a financial record that must not be deletable from the UI, however cancelled it looks.
// Deleting a paid order would also destroy the only record of what was sold (order_spec, TD-465) and
// the tax columns v3.0.425 exists to preserve.
//
// THE FILES GO WITH IT, WHICH IS THE WHOLE POINT. keyFromUrl did not know the 'print' prefix until
// this same build (see storage.js) -- written before that fix, this route would have deleted the row
// and left both PDFs in the bucket, doing the reverse of what it is for. The releases are
// best-effort and logged: a bucket that refuses must not strand the row the reader asked to remove.
router.delete('/orders/:id', requireSession, async function (req, res) {
  const userId = req.session.userId;
  const id = parseInt(req.params.id, 10);
  if (!Number.isFinite(id)) return res.status(400).json({ error: 'Bad order id' });
  try {
    const db = await getDb();
    const row = await db.prepare(
      'SELECT id, user_id, payment_status, interior_pdf_url, cover_pdf_url FROM print_orders WHERE id = ?'
    ).get(id);
    if (!row || row.user_id !== userId) return res.status(404).json({ error: 'Order not found' });
    if (row.payment_status === 'paid' || row.payment_status === 'refunded') {
      return res.status(409).json({ error: 'This order was paid for, so it stays on your record. It cannot be deleted.' });
    }
    const storage = require('../storage/storage');
    for (const u of [row.interior_pdf_url, row.cover_pdf_url]) {
      if (!u) continue;
      try { await storage.deleteFile(u); }
      catch (e) { console.error('order delete: could not release', u, e && e.message); }
    }
    await db.prepare('DELETE FROM print_orders WHERE id = ? AND user_id = ?').run(id, userId);
    return res.json({ success: true, id: id });
  } catch (e) {
    console.error('order delete error:', e && e.message);
    return res.status(500).json({ error: 'Could not delete that order.' });
  }
});

// fulfillPrintOrder(session) -- webhook fulfillment for a paid book order
// (checkout.session.completed with metadata.kind === 'print_order'). Payment
// has cleared, so NOW submit the job to the vendor. Idempotent: a duplicate
// delivery that finds the order already submitted does nothing. Exported and
// called from the Stripe webhook in routes/tokens.js.
// ------------------------------------------------------------
async function fulfillPrintOrder(session, eventId) {
  if (!session || !session.metadata) return;
  const orderId = parseInt(session.metadata.order_id, 10);
  if (!orderId) return;
  const db = await getDb();
  const row = await db.prepare('SELECT * FROM print_orders WHERE id = ?').get(orderId);
  if (!row) return;
  // Idempotency: already submitted to the vendor -> nothing to do.
  if (row.provider_order_id) return;

  // 1) Mark paid + capture the Stripe payment id and (best-effort) card display.
  const paymentIntentId = (session.payment_intent && typeof session.payment_intent === 'object')
    ? session.payment_intent.id : (session.payment_intent || null);
  let cardBrand = null, cardLast4 = null;
  try {
    const card = await stripeProvider.cardForPayment(paymentIntentId);
    if (card) { cardBrand = card.brand || null; cardLast4 = card.last4 || null; }
  } catch (e) {}
  await db.prepare(
    'UPDATE print_orders SET payment_status = ?, status = ?, stripe_payment_intent_id = ?, card_brand = ?, card_last4 = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?'
  ).run('paid', 'paid', paymentIntentId, cardBrand, cardLast4, orderId);
  // Account-lifecycle: a real purchase resets the lone-copper idle clock.
  try { await db.prepare('UPDATE users SET last_purchase_at = ? WHERE id = ?').run(new Date().toISOString(), row.user_id); } catch (e) {}

  // 2) Resolve contact + submit to the vendor now that payment cleared.
  const externalId = row.external_id || ('po-' + orderId);
  let contactEmail = null, contactName = null;
  try {
    const u = await db.prepare('SELECT name, email FROM users WHERE id = ?').get(row.user_id);
    contactEmail = u && u.email ? u.email : null;
    contactName = u && u.name ? u.name : null;
  } catch (e) {}

  try {
    // v3.0.783 -- TD-579. THE PAPER HAS TO SURVIVE THE ROUND TRIP.
    // paper was not passed, and buildSpec ends with `paper: sel.paper === 'cream' ? 'cream' :
    // 'white'` -- so an absent value became WHITE, silently. paper is part of the vendor SKU, so
    // a cream order was quoted as cream, charged as cream and submitted as white, with the row
    // holding the right value and nothing on the submission path reading it. Nothing threw and
    // nothing logged. The column was added in v3.0.667 precisely because paper swaps the SKU and
    // the price; this path never caught up.
    const built = catalog.buildSpec(
      { binding: row.binding, colorTier: row.color_tier, coverFinish: row.cover_finish,
        paper: row.paper || undefined },
      parseInt(row.page_count, 10)
    );
    if (!built.ok) throw new Error('Stored selection invalid: ' + (built.errors || []).join('; '));
    const provider = getPrintProvider();
    const orderReq = buildOrderRequestFromRow(row, built.spec, externalId, contactEmail);
    const placed = await provider.createOrder(orderReq);
    // Tracking is left null until Lulu returns it (picked up by the /order/:id
    // status refresh once the job ships). We deliberately do NOT invent one.
    await db.prepare(
      'UPDATE print_orders SET provider_order_id = ?, status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?'
    ).run(placed.providerOrderId, placed.status || 'created', orderId);
    if (contactEmail) {
      sendOrderConfirmationEmail({
        to_email: contactEmail, name: contactName,
        order: {
          orderNo: externalId, providerOrderId: placed.providerOrderId,
          bookTitle: row.book_title, orderName: row.order_name, campaignName: row.campaign_name,
          binding: row.binding, colorTier: row.color_tier, coverFinish: row.cover_finish,
          pageCount: row.page_count, quantity: row.quantity,
          total: row.customer_charge, currency: row.currency,
          cardBrand: cardBrand, cardLast4: cardLast4,
          trackingNumber: null, trackingUrl: null,
          shipTo: { name: row.ship_name, street1: row.ship_street1, street2: row.ship_street2, city: row.ship_city, stateCode: row.ship_state, postcode: row.ship_postcode, countryCode: row.ship_country }
        }
      });
    }
  } catch (submitErr) {
    // v3.0.786 -- TD-587. BEFORE CALLING IT A FAILURE, GO AND LOOK.
    // A refusal (4xx) is certain and needs no lookup. Anything else -- a timeout, a 5xx, a dropped
    // socket -- may have created the job anyway, which is exactly what happened to po-7: Cloudflare
    // returned 504, print job 3006840 existed, and we recorded the order as never sent.
    // Three attempts over about half a minute, because Lulu does not necessarily index a new job
    // the instant it is created and asking once would answer "no" too confidently.
    var _refused = !!(submitErr && submitErr.refused);
    if (!_refused) {
      for (var _try = 0; _try < 3; _try++) {
        await new Promise(function (r) { setTimeout(r, 5000 + _try * 5000); });
        var _rec = await recoverPrintJob(db, row);
        if (_rec.found) {
          try {
            console.log('[order-recover] ' + externalId + ' recovered after a failed submit -- the job existed all along');
          } catch (e) {}
          if (contactEmail) {
            sendOrderConfirmationEmail({
              to_email: contactEmail, name: contactName,
              order: {
                orderNo: externalId, providerOrderId: _rec.providerOrderId,
                bookTitle: row.book_title, orderName: row.order_name, campaignName: row.campaign_name,
                binding: row.binding, colorTier: row.color_tier, coverFinish: row.cover_finish,
                pageCount: row.page_count, quantity: row.quantity,
                total: row.customer_charge, currency: row.currency,
                cardBrand: cardBrand, cardLast4: cardLast4,
                trackingNumber: null, trackingUrl: null,
                shipTo: { name: row.ship_name, street1: row.ship_street1, street2: row.ship_street2, city: row.ship_city, stateCode: row.ship_state, postcode: row.ship_postcode, countryCode: row.ship_country }
              }
            });
          }
          return;   // the order succeeded; only the reply was lost
        }
        if (_rec.found === false) break;   // Lulu answered and has nothing: stop asking
      }
    }
    // Paid but the print job did not go -> flag for refund/retry.
    // v3.0.782 -- TD-577. SAY THAT NOTHING REACHED THE PRINTER.
    // order_failed means the SUBMISSION threw: no print job was created, no id was minted,
    // the files were never downloaded, and nothing appears in the vendor dashboard. That is a
    // different event from `rejected`, which means the printer took the job and then refused
    // the files -- and the reader was being told the second story for both. The prefix travels
    // with the row so every surface that shows `error` inherits the distinction instead of
    // each one having to re-derive it.
    // v3.0.786 -- TD-587. THREE OUTCOMES, NOT TWO.
    //   order_failed  -- refused, and the recovery lookup confirmed no job exists. Safe to reorder.
    //   order_unknown -- we could not establish whether a job exists. NOT safe to reorder.
    // v3.0.782 wrote "NOT SENT TO THE PRINTER" on both, which was a promise we could not keep and
    // which sat in front of a Reorder button.
    var _msg = String((submitErr && submitErr.message) || submitErr);
    var _state = _refused ? 'order_failed' : 'order_unknown';
    var _prefix = _refused
      ? 'NOT SENT TO THE PRINTER: '
      : 'MAY OR MAY NOT HAVE REACHED THE PRINTER -- check external id ' + externalId + ': ';
    if (_msg.indexOf('NOT SENT') !== 0 && _msg.indexOf('MAY OR MAY NOT') !== 0) _msg = _prefix + _msg;
    await db.prepare(
      'UPDATE print_orders SET status = ?, error = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?'
    ).run(_state, _msg, orderId);
    if (contactEmail) {
      sendOrderProblemEmail({
        to_email: contactEmail, name: contactName,
        order: {
          orderNo: externalId, bookTitle: row.book_title, orderName: row.order_name,
          campaignName: row.campaign_name, binding: row.binding, colorTier: row.color_tier,
          coverFinish: row.cover_finish, pageCount: row.page_count, quantity: row.quantity
        }
      });
    }
    // v3.0.783 -- TD-582. A SEPARATE REPORT TO SUPPORT, BECAUSE IT IS A SEPARATE AUDIENCE.
    //
    // Ian wants everything needed to research and refund a failed order in one message. The
    // obvious move was to put it in the customer email, which already BCC'd support -- and that
    // is the one thing this file's own rule forbids: TWO AUDIENCES SHARING ONE STRING IS ALWAYS
    // A BUG (TD-513, where 1500 characters of raw model output written for a log reached a
    // reader in a 2.5-second toast). The customer gets a sentence and an action; support gets
    // the Stripe payment id, the amounts and the vendor error. One body cannot serve both.
    //
    // Sent even when contactEmail is missing -- an order whose owner has no email is MORE in
    // need of a report, not less, so this deliberately sits outside the block above.
    //
    // NEVER FATAL, and never silent: the whole point is that a paid order which did not ship
    // must reach a human, so a send failure falls back to the server log carrying the same
    // fields rather than being swallowed.
    try {
      await sendOrderFailureReport({
        orderId: orderId,
        externalId: externalId,
        customerEmail: contactEmail,
        customerName: contactName,
        userId: row.user_id,
        providerOrderId: row.provider_order_id || null,
        amount: row.customer_charge,
        currency: row.currency,
        orderName: row.order_name,
        bookTitle: row.book_title,
        campaignName: row.campaign_name,
        stripePaymentIntentId: paymentIntentId || null,
        stripeSessionId: row.stripe_session_id || null,
        cardBrand: cardBrand, cardLast4: cardLast4,
        binding: row.binding, colorTier: row.color_tier, coverFinish: row.cover_finish,
        paper: row.paper, pageCount: row.page_count, quantity: row.quantity,
        providerCost: row.provider_cost, providerTax: row.provider_tax,
        interiorPdfUrl: row.interior_pdf_url, coverPdfUrl: row.cover_pdf_url,
        error: _msg
      });
    } catch (reportErr) {
      try {
        console.error('[order-failure] the support report could not be sent: ' +
          ((reportErr && reportErr.message) || reportErr) +
          ' -- order ' + externalId + ' user ' + row.user_id + ' <' + (contactEmail || 'no email') + '>' +
          ' charged ' + row.customer_charge + ' ' + row.currency +
          ' stripe_pi ' + (paymentIntentId || 'none') +
          ' lulu ' + (row.provider_order_id || 'none') +
          ' error: ' + _msg);
      } catch (e2) {}
    }
  }
}

router.fulfillPrintOrder = fulfillPrintOrder;

module.exports = router;
