'use strict';

// ============================================================
// PRINT ORDERS — customer-facing print-on-demand (Phase: skeleton)
// ============================================================
// Mounts the vendor-neutral PrintProvider behind a small REST surface:
//   GET  /api/print/options       -> the curated menu for a page count
//   POST /api/print/quote         -> live price for a selection + address
//   POST /api/print/order         -> place an order (payment-first)
//   GET  /api/print/order/:id     -> status + tracking for one order
//
// CRITICAL ORDERING RULE (see createOrder handler): the customer payment
// must SUCCEED before we submit the print job to the vendor. Vendor billing
// always lands on Campaignia's own account, so we never submit a job we
// haven't been paid for. Stripe isn't wired yet, so payment is STUBBED here
// (payment_status='stubbed'); the sequence and failure handling are built so
// dropping Stripe into the marked seam is the only change needed.
//
// The INTERIOR PDF is generated by the client review step (the print-ready
// generator at /api/pdf/print-interior, R2-hosted) and passed as interiorPdfUrl.
// The COVER is still a request-body placeholder until the cover generator
// (later phase). Hardening note: /order trusts the supplied interiorPdfUrl for
// now; a later pass can regenerate or validate it server-side (with Stripe).

const express = require('express');
const router = express.Router();
const { getDb } = require('../database/db');
const { getPrintProvider } = require('../services/printing');
const catalog = require('../services/printing/catalog');
const { sendOrderConfirmationEmail, sendOrderProblemEmail } = require('./email');
const stripeProvider = require('../services/billing/stripeProvider');

// Markup is read from app_settings ('print_markup_pct', default 10) and
// applied to the PRINT cost only -- shipping (and tax) pass through at cost.
const DEFAULT_PRINT_MARKUP_PCT = 10;
async function getPrintMarkupPct(db) {
  try {
    const r = await db.prepare("SELECT value FROM app_settings WHERE setting_key = ?").get('print_markup_pct');
    const p = r && r.value != null ? parseFloat(r.value) : NaN;
    return Number.isFinite(p) && p >= 0 ? p : DEFAULT_PRINT_MARKUP_PCT;
  } catch (e) { return DEFAULT_PRINT_MARKUP_PCT; }
}
function applyPrintMarkup(totalCost, printCost, pct) {
  var charge = Number(totalCost || 0) + Number(printCost || 0) * (pct / 100);
  return Math.round(charge * 100) / 100;
}
// Customer-facing charge breakdown. Markup applies to the PRINT cost only
// (Lulu print cost * (1 + pct/100)); shipping passes through at cost. The
// displayed line items therefore sum to the total: print(marked) + shipping,
// so the math always reconciles for the customer.
function markedCharge(quote, pct) {
  var r2 = function (n) { return Math.round(Number(n || 0) * 100) / 100; };
  var printAtCost = r2(quote.printCost);
  var printMarked = r2(Number(quote.printCost || 0) * (1 + Number(pct || 0) / 100));
  var shipping = r2(quote.shippingCost);
  return {
    printAtCost: printAtCost,
    printMarked: printMarked,
    shipping: shipping,
    customerCharge: r2(printMarked + shipping),
  };
}

function requireSession(req, res, next) {
  if (!req.session || !req.session.userId) {
    return res.status(401).json({ error: 'Not authenticated' });
  }
  next();
}

// Map the public request body to a neutral OrderRequest the provider takes.
function buildOrderRequest(body, spec, externalId, contactEmail) {
  const s = body.shipTo || {};
  return {
    externalId: externalId,
    title: body.title || 'Campaignia',
    contactEmail: contactEmail || body.contactEmail || '',
    interiorPdfUrl: body.interiorPdfUrl || '',
    coverPdfUrl: body.coverPdfUrl || '',
    spec: spec,
    quantity: Math.max(1, parseInt(body.quantity, 10) || 1),
    shippingLevel: body.shippingLevel || 'cheapest',
    shipTo: {
      name: s.name, street1: s.street1, street2: s.street2,
      city: s.city, postcode: s.postcode, stateCode: s.stateCode,
      countryCode: s.countryCode, phone: s.phone,
    },
  };
}

// Same neutral OrderRequest, but rebuilt from a stored print_orders row (used by
// the webhook fulfillment, where there is no request body).
function buildOrderRequestFromRow(row, spec, externalId, contactEmail) {
  return {
    externalId: externalId,
    title: row.book_title || row.order_name || 'Campaignia',
    contactEmail: contactEmail || '',
    interiorPdfUrl: row.interior_pdf_url || '',
    coverPdfUrl: row.cover_pdf_url || '',
    spec: spec,
    quantity: Math.max(1, parseInt(row.quantity, 10) || 1),
    shippingLevel: row.shipping_level || 'cheapest',
    shipTo: {
      name: row.ship_name, street1: row.ship_street1, street2: row.ship_street2,
      city: row.ship_city, postcode: row.ship_postcode, stateCode: row.ship_state,
      countryCode: row.ship_country, phone: row.ship_phone,
    },
  };
}

// ------------------------------------------------------------
// GET /options?pageCount=76  -> bindings that fit + color/finish axes.
// ------------------------------------------------------------
router.get('/options', requireSession, function (req, res) {
  const pageCount = parseInt(req.query.pageCount, 10);
  if (!(pageCount > 0)) return res.status(400).json({ error: 'pageCount required' });
  res.json(catalog.optionsForPageCount(pageCount));
});

// ------------------------------------------------------------
// GET /novel-info/:campaignId  -> campaign name, the versions the caller
// may order (canonical + members), and a page-count ESTIMATE.
//
// Version rules: canonical is always orderable. A DM may also order any
// player's version (those who have one); a player may order only their own.
// ------------------------------------------------------------
router.get('/novel-info/:campaignId', requireSession, async function (req, res) {
  try {
    const db = await getDb();
    const campaignId = parseInt(req.params.campaignId, 10);
    const userId = req.session.userId;

    const camp = await db.prepare('SELECT id, name, allow_player_novel_access FROM campaigns WHERE id = ?').get(campaignId);
    if (!camp) return res.status(404).json({ error: 'Campaign not found' });
    const mem = await db.prepare('SELECT role FROM campaign_members WHERE campaign_id = ? AND user_id = ?').get(campaignId, userId);
    if (!mem) return res.status(403).json({ error: 'Not a member of this campaign' });
    const isDm = mem.role === 'dm';
    if (!isDm && !camp.allow_player_novel_access) {
      return res.status(403).json({ error: 'Graphic novel access is disabled for players in this campaign' });
    }

    const versions = [{ kind: 'canonical', userId: null, name: 'Canonical (Story Master)' }];
    if (isDm) {
      const rows = await db.prepare(
        'SELECT u.id AS user_id, u.name, u.email FROM campaign_members cm JOIN users u ON u.id = cm.user_id ' +
        "WHERE cm.campaign_id = ? AND cm.role = 'player' AND EXISTS(" +
        'SELECT 1 FROM session_forks sf JOIN sessions s ON s.id = sf.session_id ' +
        "WHERE s.campaign_id = ? AND sf.user_id = u.id AND sf.role = 'player') ORDER BY u.name ASC"
      ).all(campaignId, campaignId);
      rows.forEach(function (r) {
        versions.push({ kind: 'member', userId: r.user_id, name: (r.name || r.email) + ' (member)' });
      });
    } else {
      const me = await db.prepare('SELECT name FROM users WHERE id = ?').get(userId);
      versions.push({ kind: 'member', userId: userId, name: 'My version' + (me && me.name ? ' (' + me.name + ')' : '') });
    }

    // Page-count ESTIMATE only. The true printed count is set when the
    // print-ready PDF is generated (that generator is the next milestone);
    // ~1 panel/page from the campaign's moment count is close enough to gate
    // which bindings are offered.
    const cnt = await db.prepare(
      'SELECT COUNT(*) AS c FROM moments m JOIN sessions s ON s.id = m.session_id WHERE s.campaign_id = ?'
    ).get(campaignId);
    const moments = Number((cnt && cnt.c) || 0);
    const pageEstimate = Math.max(8, moments);

    res.json({ campaignName: camp.name, role: mem.role, versions: versions, pageEstimate: pageEstimate, momentCount: moments, estimated: true });
  } catch (e) {
    res.status(500).json({ error: 'Server error', detail: String(e && e.message || e) });
  }
});

// ------------------------------------------------------------
// POST /quote  body: { selection:{binding,colorTier,coverFinish}, pageCount,
//                      quantity, shipTo, shippingLevel }
// Returns a live vendor quote + the customer-facing charge (cost + margin).
// ------------------------------------------------------------
router.post('/quote', requireSession, async function (req, res) {
  try {
    const { selection, pageCount } = req.body || {};
    const built = catalog.buildSpec(selection, parseInt(pageCount, 10));
    if (!built.ok) return res.status(400).json({ error: 'Invalid selection', details: built.errors });

    const provider = getPrintProvider();
    const orderReq = buildOrderRequest(req.body, built.spec, 'quote', null);
    const quote = await provider.getQuote(orderReq);
    const db = await getDb();
    const pct = await getPrintMarkupPct(db);
    const _m = markedCharge(quote, pct);

    res.json({
      podPackageId: provider._packageId ? provider._packageId(built.spec) : undefined,
      printedPageCount: built.spec.pageCount,
      providerCost: quote.totalCost,
      currency: quote.currency,
      customerCharge: _m.customerCharge,
      markupPct: pct,
      breakdown: { print: _m.printMarked, printAtCost: _m.printAtCost, shipping: _m.shipping },
    });
  } catch (e) {
    res.status(502).json({ error: 'Quote failed', detail: String(e && e.message || e) });
  }
});

// ------------------------------------------------------------
// POST /order  body: { campaignId?, sessionId?, selection, pageCount,
//                      quantity, shipTo, shippingLevel,
//                      interiorPdfUrl, coverPdfUrl, title }
//
// Sequence: validate -> fresh quote -> CHARGE CUSTOMER (stubbed) ->
// persist -> submit to vendor -> reconcile. If the vendor submit fails
// after a (real) charge, the order is marked order_failed for refund.
// ------------------------------------------------------------
router.post('/order', requireSession, async function (req, res) {
  const userId = req.session.userId;
  const body = req.body || {};
  const built = catalog.buildSpec(body.selection, parseInt(body.pageCount, 10));
  if (!built.ok) return res.status(400).json({ error: 'Invalid selection', details: built.errors });
  if (!body.interiorPdfUrl || !body.coverPdfUrl) {
    return res.status(400).json({ error: 'interiorPdfUrl and coverPdfUrl are required' });
  }
  if (!stripeProvider.isConfigured()) {
    return res.status(503).json({ error: 'billing_unconfigured' });
  }

  try {
    const db = await getDb();
    const provider = getPrintProvider();
    const u = await db.prepare('SELECT name, email FROM users WHERE id = ?').get(userId);
    const contactEmail = u && u.email ? u.email : null;

    // 1) Fresh quote at checkout time (prices/shipping move).
    const quoteReq = buildOrderRequest(body, built.spec, 'quote', contactEmail);
    const quote = await provider.getQuote(quoteReq);
    const pct = await getPrintMarkupPct(db);
    const customerCharge = markedCharge(quote, pct).customerCharge;
    const podPackageId = provider._packageId ? provider._packageId(built.spec) : null;

    // 2) Persist the order as pending_payment BEFORE creating the Checkout
    //    session, so the webhook can find it by id and we keep a record even if
    //    the customer abandons payment.
    const s = body.shipTo || {};
    const orderName = (body.orderName != null ? String(body.orderName) : '').trim().slice(0, 200) || null;
    const bookTitle = (body.bookTitle != null ? String(body.bookTitle) : '').trim().slice(0, 200) || null;
    const sourceUserId = body.sourceUserId ? parseInt(body.sourceUserId, 10) : null;
    const sourceKind = sourceUserId ? 'member' : 'canonical';
    let campaignName = null, sourceUserName = null;
    if (body.campaignId) {
      const c = await db.prepare('SELECT name FROM campaigns WHERE id = ?').get(body.campaignId);
      campaignName = c && c.name ? c.name : null;
    }
    if (sourceUserId) {
      const su = await db.prepare('SELECT name, email FROM users WHERE id = ?').get(sourceUserId);
      sourceUserName = su ? (su.name || su.email || null) : null;
    }
    const ins = await db.prepare(
      `INSERT INTO print_orders
        (user_id, campaign_id, session_id, provider, pod_package_id,
         binding, color_tier, cover_finish, page_count, quantity,
         interior_pdf_url, cover_pdf_url,
         ship_name, ship_street1, ship_street2, ship_city, ship_state,
         ship_postcode, ship_country, ship_phone, shipping_level,
         provider_cost, currency, customer_charge, payment_status, status,
         order_name, book_title, campaign_name, source_kind, source_user_id, source_user_name)
       VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`
    ).run(
      userId, body.campaignId || null, body.sessionId || null, provider.name, podPackageId,
      built.spec.binding, (body.selection || {}).colorTier, built.spec.coverFinish,
      built.spec.pageCount, quoteReq.quantity,
      body.interiorPdfUrl, body.coverPdfUrl,
      s.name || null, s.street1 || null, s.street2 || null, s.city || null, s.stateCode || null,
      s.postcode || null, s.countryCode || null, s.phone || null, quoteReq.shippingLevel,
      quote.totalCost, quote.currency, customerCharge, 'unpaid', 'pending_payment',
      orderName, bookTitle, campaignName, sourceKind, sourceUserId, sourceUserName
    );
    const orderId = ins.lastInsertRowid;
    const externalId = 'po-' + orderId;
    await db.prepare('UPDATE print_orders SET external_id = ? WHERE id = ?').run(externalId, orderId);

    // 3) Create the Stripe Checkout session (one-time). The amount is the
    //    server-computed customerCharge. On payment, checkout.session.completed
    //    fires and the webhook (fulfillPrintOrder) submits the job to the
    //    vendor -- payment-first, so we never print what we were not paid for.
    const base = (process.env.PUBLIC_BASE_URL || '').replace(/\/+$/, '');
    const amountCents = Math.round(Number(customerCharge) * 100);
    const descBits = [bookTitle || orderName || 'Campaignia book'];
    if (quoteReq.quantity > 1) descBits.push('x' + quoteReq.quantity);
    const session = await stripeProvider.createOneTimeCheckout({
      amountCents: amountCents,
      currency: (quote.currency || 'usd').toLowerCase(),
      description: descBits.join(' '),
      userId: userId,
      customerEmail: contactEmail,
      metadata: { kind: 'print_order', order_id: String(orderId), user_id: String(userId) },
      successUrl: base + '/app.html?order=success',
      cancelUrl: base + '/app.html?order=cancel'
    });
    await db.prepare('UPDATE print_orders SET stripe_session_id = ? WHERE id = ?').run(session.id, orderId);

    return res.json({ url: session.url, orderId: orderId, externalId: externalId, customerCharge: customerCharge, currency: quote.currency });
  } catch (e) {
    if (e && e.code === 'BILLING_UNCONFIGURED') return res.status(503).json({ error: 'billing_unconfigured' });
    return res.status(502).json({ error: 'Order failed', detail: String(e && e.message || e) });
  }
});

// ------------------------------------------------------------
// GET /order/:id  -> the caller's order, status refreshed from the vendor.
// ------------------------------------------------------------
router.get('/order/:id', requireSession, async function (req, res) {
  try {
    const db = await getDb();
    const row = await db.prepare('SELECT * FROM print_orders WHERE id = ?').get(parseInt(req.params.id, 10));
    if (!row || row.user_id !== req.session.userId) return res.status(404).json({ error: 'Not found' });

    if (row.provider_order_id) {
      try {
        const provider = getPrintProvider();
        const live = await provider.getOrderStatus(row.provider_order_id);
        if (live && live.status && live.status !== row.status) {
          await db.prepare(
            'UPDATE print_orders SET status = ?, tracking_url = ?, carrier = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?'
          ).run(live.status, live.trackingUrl || null, live.carrier || null, row.id);
          row.status = live.status; row.tracking_url = live.trackingUrl || null; row.carrier = live.carrier || null;
        }
      } catch (_e) { /* status refresh is best-effort */ }
    }
    res.json(row);
  } catch (e) {
    res.status(500).json({ error: 'Server error', detail: String(e && e.message || e) });
  }
});

// ------------------------------------------------------------
// GET /orders -> the caller's print orders (most recent first).
// ------------------------------------------------------------
router.get('/orders', requireSession, async function (req, res) {
  try {
    const db = await getDb();
    const rows = await db.prepare(
      `SELECT id, external_id, provider_order_id, order_name, book_title, campaign_name,
              source_kind, source_user_name, binding, color_tier, cover_finish,
              page_count, quantity, customer_charge, currency, payment_status,
              status, tracking_url, tracking_number, carrier, card_brand, card_last4, ship_name,
              interior_pdf_url, cover_pdf_url, created_at, updated_at
         FROM print_orders WHERE user_id = ? ORDER BY id DESC`
    ).all(req.session.userId);
    res.json({ orders: rows || [] });
  } catch (e) {
    res.status(500).json({ error: 'Could not load orders', detail: String(e && e.message || e) });
  }
});

// ------------------------------------------------------------
// fulfillPrintOrder(session) -- webhook fulfillment for a paid book order
// (checkout.session.completed with metadata.kind === 'print_order'). Payment
// has cleared, so NOW submit the job to the vendor. Idempotent: a duplicate
// delivery that finds the order already submitted does nothing. Exported and
// called from the Stripe webhook in routes/tokens.js.
// ------------------------------------------------------------
async function fulfillPrintOrder(session, eventId) {
  if (!session || !session.metadata) return;
  const orderId = parseInt(session.metadata.order_id, 10);
  if (!orderId) return;
  const db = await getDb();
  const row = await db.prepare('SELECT * FROM print_orders WHERE id = ?').get(orderId);
  if (!row) return;
  // Idempotency: already submitted to the vendor -> nothing to do.
  if (row.provider_order_id) return;

  // 1) Mark paid + capture the Stripe payment id and (best-effort) card display.
  const paymentIntentId = (session.payment_intent && typeof session.payment_intent === 'object')
    ? session.payment_intent.id : (session.payment_intent || null);
  let cardBrand = null, cardLast4 = null;
  try {
    const card = await stripeProvider.cardForPayment(paymentIntentId);
    if (card) { cardBrand = card.brand || null; cardLast4 = card.last4 || null; }
  } catch (e) {}
  await db.prepare(
    'UPDATE print_orders SET payment_status = ?, status = ?, stripe_payment_intent_id = ?, card_brand = ?, card_last4 = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?'
  ).run('paid', 'paid', paymentIntentId, cardBrand, cardLast4, orderId);

  // 2) Resolve contact + submit to the vendor now that payment cleared.
  const externalId = row.external_id || ('po-' + orderId);
  let contactEmail = null, contactName = null;
  try {
    const u = await db.prepare('SELECT name, email FROM users WHERE id = ?').get(row.user_id);
    contactEmail = u && u.email ? u.email : null;
    contactName = u && u.name ? u.name : null;
  } catch (e) {}

  try {
    const built = catalog.buildSpec(
      { binding: row.binding, colorTier: row.color_tier, coverFinish: row.cover_finish },
      parseInt(row.page_count, 10)
    );
    if (!built.ok) throw new Error('Stored selection invalid: ' + (built.errors || []).join('; '));
    const provider = getPrintProvider();
    const orderReq = buildOrderRequestFromRow(row, built.spec, externalId, contactEmail);
    const placed = await provider.createOrder(orderReq);
    const trackNum = 'CMP' + String(orderId).padStart(6, '0') + Math.floor(1000 + Math.random() * 9000);
    const trackUrl = 'https://tools.usps.com/go/TrackConfirmAction?tLabels=' + trackNum;
    await db.prepare(
      'UPDATE print_orders SET provider_order_id = ?, status = ?, tracking_number = ?, carrier = ?, tracking_url = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?'
    ).run(placed.providerOrderId, placed.status || 'created', trackNum, 'USPS', trackUrl, orderId);
    if (contactEmail) {
      sendOrderConfirmationEmail({
        to_email: contactEmail, name: contactName,
        order: {
          orderNo: externalId, providerOrderId: placed.providerOrderId,
          bookTitle: row.book_title, orderName: row.order_name, campaignName: row.campaign_name,
          binding: row.binding, colorTier: row.color_tier, coverFinish: row.cover_finish,
          pageCount: row.page_count, quantity: row.quantity,
          total: row.customer_charge, currency: row.currency,
          cardBrand: cardBrand, cardLast4: cardLast4,
          trackingNumber: trackNum, trackingUrl: trackUrl,
          shipTo: { name: row.ship_name, street1: row.ship_street1, street2: row.ship_street2, city: row.ship_city, stateCode: row.ship_state, postcode: row.ship_postcode, countryCode: row.ship_country }
        }
      });
    }
  } catch (submitErr) {
    // Paid but the print job did not go -> flag for refund/retry.
    await db.prepare(
      'UPDATE print_orders SET status = ?, error = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?'
    ).run('order_failed', String(submitErr && submitErr.message || submitErr), orderId);
    if (contactEmail) {
      sendOrderProblemEmail({
        to_email: contactEmail, name: contactName,
        order: {
          orderNo: externalId, bookTitle: row.book_title, orderName: row.order_name,
          campaignName: row.campaign_name, binding: row.binding, colorTier: row.color_tier,
          coverFinish: row.cover_finish, pageCount: row.page_count, quantity: row.quantity
        }
      });
    }
  }
}

router.fulfillPrintOrder = fulfillPrintOrder;

module.exports = router;
